name: Build Book PDF

on:
  push:
    # Tag push starting with v triggers PDF build and release
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-lang-japanese fonts-noto-cjk
      - name: Combine Markdown files
        run: |
          mkdir -p build
          ls chapters/*.md | sort | xargs cat > build/book.md
      - name: Convert to PDF
        run: |
          pandoc build/book.md --defaults pandoc/latex.yaml -o build/book.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: build/book.pdf
      - name: Create Release and attach PDF
        uses: softprops/action-gh-release@v1
        with:
          files: build/book.pdf
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
